server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${music.datasource.driver-class-name}
      url: jdbc:mysql://${music.datasource.host}:${music.datasource.port}/${music.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${music.datasource.username}
      password: ${music.datasource.password}
  redis:
    host: ${music.redis.host}
    port: ${music.redis.port}
    password: ${music.redis.password}
    database: ${music.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.music.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      music:
        mapper: debug
        service: info
        controller: info


