music:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: music_platform
    username: root
    password: 123456


#  redis:
#    host: localhost
#    port: 6379
#    database: 10
#  wechat:
#    appid: wx58d0eab6e8f14385
#    secret: bb878e5be50200be59d1c62f80b57b10